### ISSUE TITLE
Change the event time

### ISSUE THREAD

**Issue by kristjanmik** [jsis/reykjavik-js#1]
Currently we have a weekly meetup starting at 17:30 every Wednesday. I suggest that we make it biweekly and start at 19:30.

What do you think? is it better to host it before or after dinner?

**Comment by kristjanmik** [comment]
@jonrh said this in another thread:

I agree on a biweekly schedule. Starting at somewhere between 18:30 and 20:00 sounds best to me. So after dinner. As to a location, KEX is a really cool place but it's so frequently fully booked or reserved. If we go to a biweekly schedule and move to Facebook events I think it could be a cool idea to swap the places around where we meet, to mix things up a bit. Here are some of my favourite places I think may be suitable:

Loft Hostel
Stofan
Nora
American Bar
Brooklin Bar
Btw I thought we were meeting on Wednesdays, am I perhaps confusing this event to other?

**Comment by kristjanmik** [comment]
No, my bad. I was confusing this one to another one :P
Should we try to do from 19:30 to 21:30 this Wednesday(8th of July)?
@jonrh isn't loft booked often as well?

**Comment by jonrh** [comment]
It probably is yes, especially during the summer when the hostel is fully booked. I'd vote for 19:30 as well.

**Comment by koddsson** [comment]
I'm fine either way. I personally like going straight from work to a meetup with beers but I'm probably in the smaller demography.

re: the place to meet: I actually really like KEX since it will expand as our party expands. I'm having trouble trying to remember place in downtown reykjavik that will scale with us like KEX does.

Any one wanna make a PR with the time change?

**Comment by eirikurn** [comment]
Yeah +1 for 19:30 or later for this family person. Maybe then, I'll ever make it. :)

**Comment by kristjanmik** [comment]
19:30 is now the official time for the meetup. The where to host can be moved to another issue.
